Areas/Admin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using WebBanHoa.Models;

namespace WebBanHoa.Areas.Admin.Controllers
{
    public class HomeController : Controller
    {
        // GET: User
        WebBanHoaEntities1 data = new WebBanHoaEntities1();
        // GET: User
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult DangXuat()
        {
            Session.Clear();
            return RedirectToAction("Index", "Home");
        }
        public ActionResult LoginLogout()
        {
            return PartialView("LoginLogoutPartial");
        }

        [HttpGet]
        public ActionResult DangNhap()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DangNhap(FormCollection f)
        {
            var sTenDNAdmin = f["TenDNAdmin"];
            var sMatKhauAdmin = f["MatKhauAdmin"];
            if (String.IsNullOrEmpty(sTenDNAdmin))
            {
                ViewData["Err1"] = "Bạn chưa nhập tên đăng nhập";
            }
            else if (String.IsNullOrEmpty(sMatKhauAdmin))
            {
                ViewData["Err1"] = "Phải nhập mật khẩu";
            }
            else
            {
                ADMIN ad = data.ADMINs.SingleOrDefault(n => n.TenDNAdmin == sTenDNAdmin && n.MatKhauAdmin == sMatKhauAdmin);
                if (ad != null)
                {

                    ViewBag.Thongbao = "Chúc mừng đăng nhập thành công";
                    Session["TaikhoanAdmin"] = ad;
                    
                        return RedirectToAction("Index", "Home");
                   
                }
                else
                {
                    ViewBag.Thongbao = "Tên đăng nhập hoặc mật khẩu không đúng";

                }
            }
            return View();
        }

    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebBanHoa.Models;
using PagedList.Mvc;
using System.Data.Entity;
using PagedList;

namespace WebBanHoa.Controllers
{
    public class HomeController : Controller
    {
        WebBanHoaEntities1 db = new WebBanHoaEntities1();
        public ActionResult NotFound()
        {
            return View();
        }
        public ActionResult Search()
        {
            return View();
        }    
        public ActionResult Menu()
        {

            return View();
        }
        public ActionResult SlideShow()
        {

            return View();
        }
        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        //[HttpGet]
        //public ActionResult Login()
        //{
        //    return View();
        //}
        //[HttpPost]
        //public ActionResult Login(FormCollection f)
        //{
        //    var sTenDN = f["UserName"];
        //    var sMK = f["PassWord"];
        //    ADMIN ad = db.ADMINs.SingleOrDefault(n => n.TenDNAdmin == sTenDN && n.MatKhauAdmin == sMK);
        //    if (ad != null)
        //    {
        //        Session["Admin"] = ad;
        //        return RedirectToAction("Index", "Home");

        //    }
        //    else
        //    {
        //        ViewBag.ThongBao = "Tên đăng nhập hoặc mật khẩu không đúng!";
        //    }
        //    return View();
        //}

        public ActionResult Index(string searchString, int? page)
        {

            var sp = from l in db.SANPHAMs
                        select l;
            int iPageNum = (page ?? 1);
            int iPageSize = 9;
            //return View(data.SANPHAMs.ToList().OrderBy(n => n.MaSP).ToPagedList(iPageNum, iPageSize));
            if (searchString!=null)
            {
                sp = sp.Where(s => s.TenSP.Contains(searchString));
                if (sp.Count() == 0)
                {
                    
                    return RedirectToAction("NotFound", "Home");
                }
                else
                    return View(sp);
                
            }
            else
                return View(db.SANPHAMs.ToList().OrderBy(n => n.MaSP).ToPagedList(iPageNum, iPageSize));
        }
    }
}

Controllers/SanPhamHoaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using WebBanHoa.Models;
using PagedList;
using PagedList.Mvc;

namespace WebBanHoa.Controllers
{
    public class SanPhamHoaController : Controller
    {
        // GET: SanPhamHoa
        private WebBanHoaEntities1 data = new WebBanHoaEntities1();
        public ActionResult LoginLogout()
        {
            return PartialView("LoginLogoutPartial");
        }
        public ActionResult Index()
        {
            return View(data.SANPHAMs.Take(10));
        }
        public ActionResult PhanLoai()
        {
            var pl = from PL in data.PHANLOAIs select PL;
            return PartialView(pl) ;
        }
        public ActionResult SPTheoPL(int id, int? page)
        {
            ViewBag.MaPL = id;
            int iSize = 3;
            int iPageNum = (page ?? 1);
            var sp = from s in data.SANPHAMs where s.MaPL == id orderby id select s;
            return View(sp.ToPagedList(iPageNum, iSize));
        }
        public ActionResult NhaCungCap()
        {

            var NCC = from NhaCC in data.NHACUNGCAPs select NhaCC;
            return PartialView(NCC);
        }
        public ActionResult SPTheoNCC(int id, int? page)
        {
            ViewBag.MaNCC = id;
            int iSize = 3;
            int iPageNum = (page ?? 1);
            var sp = from s in data.SANPHAMs where s.MaNCC == id orderby id select s;
            return View(sp.ToPagedList(iPageNum, iSize));
        }
        public ActionResult Chitietsanpham(int id)
        {
            var sp = from s in data.SANPHAMs
                       where s.MaSP == id
                       select s;
            return View(sp.Single());
        }
    }
}

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<style type="text/css">

    .social-link {
        width: 30px;
        height: 30px;
        border: 1px solid #ddd;
        display: flex;
        align-items: center;
        justify-content: center;
        color: #666;
        border-radius: 50%;
        transition: all 0.3s;
        font-size: 0.9rem;
    }

        .social-link:hover,
        .social-link:focus {
            background: #ddd;
            text-decoration: none;
            color: #555;
        }
</style>
<section class="clearfix Pro">
    <div class="bg-light">
        <div class="container py-5">
            <div class="row h-100 align-items-center py-5">
                <div class="col-lg-6">
                    <h1 class="display-4" style="color:darkmagenta; font-weight:bold">Vài điều về EliveStore</h1>
                    <p class="lead text-muted mb-0">Hoa sáp Elives tự hào là địa chỉ tin cậy trong lĩnh vực làm hoa sáp, với đội ngũ nhân viên đầy kinh nghiệm, luôn cập nhật những mẫu hoa đẹp, sang trọng, đáp ứng nhu cầu của khách hàng. chúng tôi tự hào là nơi hội tụ những mẫu hoa đẹp và sáng tạo, luôn thay đổi để phù hợp với nhu cầu của khách hàng.</p>
                    <p class="lead text-muted">
                    </p>
                </div>
                <div class="col-lg-6 d-none d-lg-block"><img src="~/img/sp/hoasapdeban.jpg" alt="" class="img-fluid"></div>
            </div>
        </div>
    </div>

    <div class="bg-white py-5">
        <div class="container py-5">
            <div class="row align-items-center mb-5">
                <div class="col-lg-6 order-2 order-lg-1">
                    <i class="fa fa-bar-chart fa-2x mb-3 text-primary"></i>
                    <h1 class="font-weight-light" style="color:indianred">Giới thiệu về hoa tiền Elives</h1>
                    <p class="lead text-muted mb-0">
                        Là địa chỉ làm hoa tiền uy tín, cam kết làm hoa bằng tiền thật, tiền mới 100%.
                        <br />
                        Sản phẩm:
                        <br />
                        Nhằm đáp ứng nhu cầu của khách hàng, shop chúng tôi có đủ các mệnh giá tiền từ 1k,2k,5k,10k,20k,50k,100k,200k,500k, ngoài ra còn có tiền đô để các bạn thoải mái lựa chọn. Ngoài ra hoa chúng tôi có những mẫu hoa tiền kết hợp với hoa sáp, hoa baby,… rất đẹp và độc đáo.
                    </p>
                </div>
                <div class="col-lg-5 px-5 mx-auto order-1 order-lg-2"><img src="~/img/sp/hoatien100k.jpg" alt="" class="img-fluid mb-4 mb-lg-0"></div>
            </div>
            <div class="row align-items-center">
                <div class="col-lg-5 px-5 mx-auto"><img src="~/img/about-us-img.jpg" alt="" class="img-fluid mb-4 mb-lg-0"></div>
                <div class="col-lg-6">
                    <i class="fa fa-leaf fa-2x mb-3 text-primary"></i>
                    <h1 class="font-weight-light" style="color:cornflowerblue">Dịch vụ khách hàng</h1>
                    <p class="lead text-muted mb-0">
                        Tư vấn nhiệt tình, giao hàng và thanh toán nhanh.
                        <br />
                        Khi nhận được thông tin từ khách hàng, chúng tôi luôn hỗ trợ, tư vấn nhiệt tình để khách hàng có thể chọn được những sản phẩm ưng ý nhất, phù hợp nhất.
                        <br />
                        Giao hàng nhanh chóng trên toàn quốc, ship COD.
                        <br />
                        Giao hàng trong ngày cho các đơn hàng trong nội thành Hà Nội.
                        <br />
                        Luôn tiếp nhận những phản hồi, góp ý của khách hàng để hoàn thiện và nỗ lực hơn.
                    </p>
                </div>
            </div>
        </div>
    </div>

    <div class="bg-light py-5">
        <div class="container py-5">
            <div class="row mb-4">
                <div class="col-lg-5">
                    <h2 class="display-4 font-weight-light">Đội ngũ của chúng tôi</h2>
                    <p class="font-italic text-muted">Mỗi bó hoa một lời yêu thương, Chúng tôi luôn chú trọng từng chi tiết nhỏ tạo nên sự hài lòng của quý khách hàng, chỉ mong tấm chân tình ấy góp nhặt mỗi ngày một chút xây lên một “Hoa Sáp EliveStore ấm tình yêu thương”.</p>
                </div>
            </div>

            <div class="row text-center">
                <!-- Team item-->
                <div class="col-xl-3 col-sm-6 mb-5">
                    <div class="bg-white rounded shadow-sm py-5 px-4">
                        <img src="~/img/Trang1.jpg" alt="" width="100" class="img-fluid rounded-circle mb-3 img-thumbnail shadow-sm">
                        <h5 class="mb-0">Phạm Thị Huyền Trang</h5><span class="small text-uppercase text-muted">CEO - Founder</span>

                    </div>
                </div>
                <!-- End-->
                <!-- Team item-->
                <div class="col-xl-3 col-sm-6 mb-5">
                    <div class="bg-white rounded shadow-sm py-5 px-4">
                        <img src="~/img/Mai1.jpg" alt="" width="100" class="img-fluid rounded-circle mb-3 img-thumbnail shadow-sm">
                        <h5 class="mb-0">Trần Thị Hồng Mai</h5><span class="small text-uppercase text-muted">CEO - Founder</span>

                    </div>
                </div>
                <!-- End-->
                <!-- Team item-->
                <div class="col-xl-3 col-sm-6 mb-5">
                    <div class="bg-white rounded shadow-sm py-5 px-4">
                        <img src="~/img/Thai1.jpg" alt="" width="100" class="img-fluid rounded-circle mb-3 img-thumbnail shadow-sm">
                        <h5 class="mb-0">Lê Doãn Thái</h5><span class="small text-uppercase text-muted">CEO - Founder</span>

                    </div>
                </div>
                <!-- End-->
                <!-- Team item-->
                <!-- End-->

            </div>
        </div>
    </div>

</section>

Views/Home/Index.cshtml
@using WebBanHoa.Models;
@using PagedList.Mvc;
@model PagedList.PagedList<SANPHAM>
@{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="container">
    <div class="row mt-5">
        <h2 class="list-product-title">Sản Phẩm Mới</h2>
        <div class="list-product-subtitle">
            <p>Danh Sách Sản Phẩm</p>
        </div>
        <div class="row text-center">
            @foreach (var sp in Model)
            {
                <div class="col-sm-4 col-md-4 col-lg-4 col-xs-6">
                    <div class="thumbnail">
                        <img src="~/img/sp/@sp.HinhMinhHoa" alt="@sp.TenSP " ;
                             class="img-responsive img-rounded imgbook" width="380" />
                        <div class="caption">
                            <h4 style="min-height:90px;min-width:90px">
                                <a href="@Url.Action("Chitietsanpham","SanPhamHoa",new {id = sp.MaSP })">
                                    @sp.TenSP
                                    <br />
                                    <br />
                                    @Html.FormatValue(sp.DonGia, "{0:#,##0,0}")VNĐ
                            </h4>
                            <p>
                                <a href="@Url.Action("ThemGioHang","GioHang",new { ms = sp.MaSP, url = Request.Url.ToString() })" class="btn btn-primary" role="button">
                                    <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true">
                                    </span> Add to Cart
                                </a>
                            </p>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>
<!-- Thêm phân trang vào -->
    Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
    <div class="MenuTrang">
        @Html.PagedListPager(Model, page => Url.Action("Index", new { id = ViewBag.MaSP, page = page }))
    </div>

    <style>
        .MenuTrang {
            display: inline;
            text-align: center;
        }
    </style>

Views/Home/Menu.cshtml
@{
    Layout = null;
}
<li class="dropdown">
    <a class="navbar-brand" href="@Url.Action("Contact","Home")"><b style="color: darkslateblue; font-size:medium">Giới Thiệu</b></a>
</li>

<li class="dropdown">
    <a class="nav-link dropdown-toggle" href="#" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <b style="color: darkslateblue; font-size: medium">Sản Phẩm Theo Phân Loại</b>
    </a>
    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
        <li><a class="dropdown-item"> @Html.Action("PhanLoai", "SanPhamHoa")</a></li>
    </ul>
</li>
<li class="dropdown">
    <a class="nav-link dropdown-toggle" href="#" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <b style="color: darkslateblue; font-size: medium">Sản Phẩm Theo Nhà Cung Cấp</b>
    </a>
    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
        <li><a class="dropdown-item"> @Html.Action("NhaCungCap", "SanPhamHoa")</a></li>
    </ul>
</li>

Views/Home/NotFound.cshtml
@{
    ViewBag.Title = "NotFound";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row mt-5">
        <h2 class="list-product-title">Sản Phẩm Mới</h2>
        <div class="list-product-subtitle">
            <p>Danh Sách Sản Phẩm</p>
        </div>
        <div class="row text-center">
             <h4 style="font:bold; color:red">Không Tìm Thấy Sản Phẩm!</h4>
        </div>
    </div>
</div>

Views/Home/Search.cshtml
@model IEnumerable<WebBanHoa.Models.SANPHAM>
@{
    Layout = null;
}<form class="navbar-form navbar-right" role="search">
    @using (Html.BeginForm("Index", "Home", FormMethod.Get))
    {

        <div class="form-group">
            <input type="text" name="searchString" class="form-control" placeholder="Gõ Từ Khóa">
            <p style="font-style:italic; color:red; margin:0px;">
                @ViewBag.ThongBao
            </p>
        </div>
        <button type="submit" class="btn btn-default">Tìm Kiếm</button>
            
    }
</form>

Views/Home/SlideShow.cshtml
@{
    Layout = null;
}

<section class="clearfix slideshow">
    <div class="container">
        <div class="row">
            <div class="col">
                <div id="carouselExampleFade" class="carousel slide carousel-fade" data-bs-ride="carousel">
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <img src="~/img/nen.jpg" class="d-block w-100" alt="..." height="500">
                        </div>
                        <div class="carousel-item">
                            <img src="/img/sp/peonies_hydrangea_flowers_painting_jugs_flower_beauty_34870_1280x720.jpg" class="d-block w-100" alt="..." height="500">
                        </div>
                        <div class="carousel-item">
                            <img src="/img/sp/cut.jpg" class="d-block w-100" alt="..." height="500">
                        </div>
                    </div>
                    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Previous</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Next</span>
                    </button>
                </div>
            </div>
        </div>
    </div>
</section>