Models/KHACHHANG.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanHoa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACHHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHACHHANG()
        {
            this.DONDATHANGs = new HashSet<DONDATHANG>();
        }
    
        public int MaKH { get; set; }
        public string HoTenKH { get; set; }
        public string DiaChiKH { get; set; }
        public string DienThoaiKH { get; set; }
        public string TenDN { get; set; }
        public string MatKhau { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
        public string Email { get; set; }
        public Nullable<bool> DaDuyet { get; set; }
        public string HinhAnh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DONDATHANG> DONDATHANGs { get; set; }
    }
}

Areas/Admin/Controllers/KhachHangController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebBanHoa.Models;
using PagedList;
using PagedList.Mvc;

namespace WebBanHoa.Areas.Admin.Controllers
{
    public class KhachHangController : Controller
    {
        WebBanHoaEntities1 data = new WebBanHoaEntities1();
        // GET: Admin/Sach
        public ActionResult Index(int? page)
        {
            int iPageNum = (page ?? 1);
            int iPageSize = 7;
            return View(data.KHACHHANGs.ToList().OrderBy(n => n.MaKH).ToPagedList(iPageNum, iPageSize));
        }



        public ActionResult Details(int id)
        {
            var kh = data.KHACHHANGs.SingleOrDefault(n => n.MaKH == id);
            if (kh == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(kh);
        }


        [HttpGet]
        public ActionResult Delete(int id)
        {
            var kh = data.KHACHHANGs.SingleOrDefault(n => n.MaKH == id);
            if (kh == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(kh);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirm(int id, FormCollection f)
        {
            var kh = data.KHACHHANGs.SingleOrDefault(n => n.MaKH == id);
            if (kh == null)
            {
                Response.StatusCode = 404;
                return null;
            }
           
            var vietkh = (data.KHACHHANGs.Where(vs => vs.MaKH == id)).SingleOrDefault();
            if (vietkh != null)
            {
                data.KHACHHANGs.Remove(vietkh);
                data.SaveChanges();
            }
            return RedirectToAction("Index");
        }

    }

}

Areas/Admin/Views/KhachHang/Delete.cshtml
@model WebBanHoa.Models.KHACHHANG
@{ ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout_Admin.cshtml";
}
<style type="text/css">
    img {
        width: 200px;
        margin-bottom: 20px;
    }

    h3, h4 {
        color: red;
        font-weight: bold;
    }
</style>
<h2> XÁC NHẬN THÔNG TIN CẦN XÓA</h2>
<h3>Bạn quyết định xóa khách hàng này?</h3>
<h4>@Html.Raw(ViewBag.ThongBao)</h4>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Tên KH:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.HoTenKH)
        </dd>
        <dt>
            Địa Chỉ:
        </dt>
        <dd>
            @Html.Raw(@Model.DiaChiKH)
        </dd>
        <dt>
            Hình Ảnh:
        </dt>
        <dd>
            <img src="~/img/kh/@Model.HinhAnh" alt=" @Model.HoTenKH">
        </dd>
        <dt>
            Ngày Sinh:
        </dt>
        <dd>
            @Html.FormatValue(@Model.NgaySinh, "{0:dd/MM/yyyy}")
        </dd>
        <dt>
            SĐT:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DienThoaiKH)
        </dd>
        <dt>
            Email:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt>
            Tên ĐN:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TenDN)
        </dd>
        <dt>
            Mật Khẩu:
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MatKhau)
        </dd>
    </dl>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div style="margin-left:300px" class="form-actions no-color">
            <input type="submit" value="XÓA" class="btn btn-default" /> |
            @Html.ActionLink("VỀ TRANG QUẢN LÝ KHÁCH HÀNG", "Index")
        </div>
    }
</div>

Areas/Admin/Views/KhachHang/Details.cshtml
@model WebBanHoa.Models.KHACHHANG

@{
    ViewBag.Title = "Chitietsanpham";
    Layout = "~/Areas/Admin/Views/Shared/_Layout_Admin.cshtml";
}

<section style="background-color: #eee;">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-8 col-lg-6 col-xl-4">
                <div class="card text-black">
                    <i class="fab fa-apple fa-lg pt-3 pb-1 px-3"></i>
                    <img src="~/img/kh/@Model.HinhAnh"
                         class="card-img-top" alt="@Model.HoTenKH" />
                    <div class="card-body">
                        <div class="text-center">
                            <h5 class="card-title">@Model.TenDN</h5>
                            <p class="text-muted mb-4">Số Điện Thoại:@Model.DienThoaiKH</p>
                        </div>
                        <div>

                        </div>
                        <div class="d-flex justify-content-between total font-weight-bold mt-4">
                            <p> Ngày Sinh: @Html.FormatValue(@Model.NgaySinh, "{0:dd/MM/yyyy}")</p>
                            <p> Email: @Model.Email</p>
                            <p> Địa Chỉ: @Model.DiaChiKH</p>
                          
                        </div>
                        <div>
                            <a href="@Url.Action("Edit","KhachHang", new { id = Model.MaKH })" class="btn btn-warning btn-block btn-lg" role="button">Sửa</a>
                            <a href="@Url.Action("Delete","KhachHang", new { id = Model.MaKH })" class="btn btn-danger btn-block btn-lg" role="button">Xóa</a>

                        </div>
                        <div class="text-center">

                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

Areas/Admin/Views/KhachHang/Index.cshtml
@using WebBanHoa.Models
@using PagedList.Mvc
@model PagedList.PagedList<WebBanHoa.Models.KHACHHANG>


@helper Truncate(string s, int length)
{               if (s.Length < length)
    {
        @s
    }
    else
    {
        @s.Substring(0, length)
    }
}


@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout_Admin.cshtml";
}

<h2 style="text-align: center"><b> QUẢN LÝ KHÁCH HÀNG</b></h2>


<table style="text-align: center">
    <tr>
        <th style="text-align:center;width:150px">
            Tên KH
        </th>

        <th style="text-align:center;width:120px">
            Hình Ảnh
        </th>
        <th style="text-align:center;width:150px">
            Ngày Sinh
        </th>
        <th style="text-align:center;width:150px">
            SĐT
        </th>
        <th style="text-align:center;width:250px">
            Email
        </th>
        <th style="text-align:center;width:250px">
            Địa Chỉ
        </th>

        <th style="text-align:center;width:80px">
            Đã Duyệt
        </th>
        <th style="text-align:center">
        </th>
    </tr>

    @foreach (var item in Model)
    {
<tr>

    <td>
        @*Sử dụng helper để cắt TenSach lấy 50 ký tự*@
        @Truncate(item.HoTenKH, 50)
    </td>


    <td>
        <img src="~/img/kh/@item.HinhAnh" asp-append-version="true" style="width: 80px;" />
    </td>
    <td>
        @*Định dạng hiển thị*@
        @Html.FormatValue(@item.NgaySinh, "{0:dd/MM/yyyy}")
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.DienThoaiKH)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Email)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.DiaChiKH)
    </td>

    <td>
        @Html.DisplayFor(modelItem => item.DaDuyet)
    </td>
    <td>
        <a href="@Url.Action("Details", new { id = item.MaKH })" class="btn btn-primary" role="button">Chi tiết</a>
        <a href="@Url.Action("Delete", new { id = item.MaKH })" class="btn btn-danger" role="button">Xóa</a>
    </td>
</tr>
    }
</table>

@*Tạo iên kết phần trang*@
Trang @(Model.PageCount < Model.PageNumber ? 0 :
        Model.PageNumber)/@Model.PageCount
        <div class="MenuTrang">
            @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
        </div>
        <style>
            .MenuTrang {
                display: inline;
                text-align: center;
            }
        </style>